version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    depends_on:
      - db
    env_file:
      - ./.env

  app:
    image: koshelevd/storage-api:latest
    build: .
    env_file:
      - ./.env
    restart:
      always
    volumes:
      - ./storage:/opt/src/storage

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    volumes:
      - ./nginx_deploy.conf:/etc/nginx/nginx.conf
      - ./storage:/opt/www/storage:ro
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
  storage:
