"""Initial migration

Revision ID: a1cfd6be193a
Revises: 
Create Date: 2023-01-07 04:55:07.659539+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cfd6be193a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date and time of creation'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date and time of last update'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Date and time of logic deletion'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Is object marked as deleted'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='Password'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date and time of creation'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Date and time of last update'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Date and time of logic deletion'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Is object marked as deleted'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='File name'),
    sa.Column('path', sa.String(length=255), nullable=False, comment='Path to file'),
    sa.Column('size', sa.Integer(), nullable=False, comment='File size'),
    sa.Column('is_downloadable', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='User'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    op.drop_table('users')
    # ### end Alembic commands ###
